"""fix user cpe record relationships

Revision ID: 214a972ab442
Revises: 6c4fb8c749a6
Create Date: 2025-06-24 20:28:33.449267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214a972ab442'
down_revision: Union[str, None] = '6c4fb8c749a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
