"""add extended trial tracking to users

Revision ID: 57b52d573bee
Revises: d3e0468e8646
Create Date: 2025-06-21 17:49:39.299085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b52d573bee'
down_revision: Union[str, None] = 'd3e0468e8646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_extended_trial', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('extended_trial_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('initial_trial_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_accepted_extended_trial'), 'users', ['accepted_extended_trial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_accepted_extended_trial'), table_name='users')
    op.drop_column('users', 'initial_trial_completed_at')
    op.drop_column('users', 'extended_trial_accepted_at')
    op.drop_column('users', 'accepted_extended_trial')
    # ### end Alembic commands ###
