"""add_passcode_to_cpas

Revision ID: e81aab631892
Revises: bec89645bef4
Create Date: 2025-06-19 10:01:06.667845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81aab631892'
down_revision: Union[str, None] = 'bec89645bef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpas', sa.Column('passcode', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_cpas_passcode'), 'cpas', ['passcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpas_passcode'), table_name='cpas')
    op.drop_column('cpas', 'passcode')
    # ### end Alembic commands ###
