"""adding smart review functionaltya

Revision ID: 8f459fbd842c
Revises: 249bd10eb7ee
Create Date: 2025-06-23 21:13:22.413070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f459fbd842c'
down_revision: Union[str, None] = '249bd10eb7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpe_records', sa.Column('smart_insights', sa.Text(), nullable=True, comment='JSON string of smart extraction insights with multiple candidates'))
    op.add_column('cpe_records', sa.Column('suggestions', sa.Text(), nullable=True, comment='JSON string of review suggestions for user interface'))
    op.add_column('cpe_records', sa.Column('review_flags', sa.Text(), nullable=True, comment='JSON string of fields needing attention'))
    op.add_column('cpe_records', sa.Column('needs_review', sa.Boolean(), nullable=False, comment='Whether record needs human review'))
    op.add_column('cpe_records', sa.Column('review_started_at', sa.DateTime(), nullable=True, comment='When user started reviewing this certificate'))
    op.add_column('cpe_records', sa.Column('review_completed_at', sa.DateTime(), nullable=True, comment='When user completed review'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpe_records', 'review_completed_at')
    op.drop_column('cpe_records', 'review_started_at')
    op.drop_column('cpe_records', 'needs_review')
    op.drop_column('cpe_records', 'review_flags')
    op.drop_column('cpe_records', 'suggestions')
    op.drop_column('cpe_records', 'smart_insights')
    # ### end Alembic commands ###
