"""Initial migration - add CPA and ComplianceRequirement tables

Revision ID: 0d6ecd766c3c
Revises: 
Create Date: 2025-06-16 10:48:36.163346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6ecd766c3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('state_name', sa.String(length=50), nullable=True),
    sa.Column('total_hours_required', sa.Integer(), nullable=True),
    sa.Column('ethics_hours_required', sa.Integer(), nullable=True),
    sa.Column('reporting_period_months', sa.Integer(), nullable=True),
    sa.Column('renewal_deadline', sa.String(length=50), nullable=True),
    sa.Column('ce_broker_required', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_requirements_id'), 'compliance_requirements', ['id'], unique=False)
    op.create_table('cpas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('license_issue_date', sa.Date(), nullable=False),
    sa.Column('license_expiration_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('total_cpe_hours', sa.Integer(), nullable=True),
    sa.Column('ethics_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_oplc_sync', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpas_email'), 'cpas', ['email'], unique=True)
    op.create_index(op.f('ix_cpas_id'), 'cpas', ['id'], unique=False)
    op.create_index(op.f('ix_cpas_license_number'), 'cpas', ['license_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpas_license_number'), table_name='cpas')
    op.drop_index(op.f('ix_cpas_id'), table_name='cpas')
    op.drop_index(op.f('ix_cpas_email'), table_name='cpas')
    op.drop_table('cpas')
    op.drop_index(op.f('ix_compliance_requirements_id'), table_name='compliance_requirements')
    op.drop_table('compliance_requirements')
    # ### end Alembic commands ###
