"""add_ce_broker_fields_to_cpe_records

Revision ID: f2065ce3e46b
Revises: 57b52d573bee
Create Date: 2025-06-22 10:09:51.034312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2065ce3e46b'
down_revision: Union[str, None] = '57b52d573bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpe_records', sa.Column('course_type', sa.String(length=50), nullable=True))
    op.add_column('cpe_records', sa.Column('delivery_method', sa.String(length=100), nullable=True))
    op.add_column('cpe_records', sa.Column('instructional_method', sa.String(length=100), nullable=True))
    op.add_column('cpe_records', sa.Column('subject_areas', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('cpe_records', sa.Column('field_of_study', sa.String(length=100), nullable=True))
    op.add_column('cpe_records', sa.Column('ce_category', sa.String(length=50), nullable=True))
    op.add_column('cpe_records', sa.Column('nasba_sponsor_number', sa.String(length=20), nullable=True))
    op.add_column('cpe_records', sa.Column('sponsor_name', sa.String(length=255), nullable=True))
    op.add_column('cpe_records', sa.Column('course_code', sa.String(length=50), nullable=True))
    op.add_column('cpe_records', sa.Column('program_level', sa.String(length=50), nullable=True))
    op.add_column('cpe_records', sa.Column('ce_broker_exported', sa.Boolean(), nullable=True))
    op.add_column('cpe_records', sa.Column('ce_broker_export_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cpe_records', sa.Column('ce_broker_ready', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpe_records', 'ce_broker_ready')
    op.drop_column('cpe_records', 'ce_broker_export_date')
    op.drop_column('cpe_records', 'ce_broker_exported')
    op.drop_column('cpe_records', 'program_level')
    op.drop_column('cpe_records', 'course_code')
    op.drop_column('cpe_records', 'sponsor_name')
    op.drop_column('cpe_records', 'nasba_sponsor_number')
    op.drop_column('cpe_records', 'ce_category')
    op.drop_column('cpe_records', 'field_of_study')
    op.drop_column('cpe_records', 'subject_areas')
    op.drop_column('cpe_records', 'instructional_method')
    op.drop_column('cpe_records', 'delivery_method')
    op.drop_column('cpe_records', 'course_type')
    # ### end Alembic commands ###
