"""add storage_tier to cpe_records

Revision ID: da75aebad80b
Revises: 832d43f196d6
Create Date: 2025-06-18 07:10:37.612587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da75aebad80b'
down_revision: Union[str, None] = '832d43f196d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpe_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpa_license_number', sa.String(length=20), nullable=False),
    sa.Column('document_filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('cpe_credits', sa.Float(), nullable=True),
    sa.Column('ethics_credits', sa.Float(), nullable=True),
    sa.Column('course_title', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('parsing_method', sa.String(length=50), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsing_notes', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('storage_tier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpe_records_cpa_license_number'), 'cpe_records', ['cpa_license_number'], unique=False)
    op.create_index(op.f('ix_cpe_records_id'), 'cpe_records', ['id'], unique=False)
    op.create_table('cpe_upload_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpa_license_number', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('documents_uploaded', sa.Integer(), nullable=True),
    sa.Column('documents_processed', sa.Integer(), nullable=True),
    sa.Column('total_credits_found', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpe_upload_sessions_cpa_license_number'), 'cpe_upload_sessions', ['cpa_license_number'], unique=False)
    op.create_index(op.f('ix_cpe_upload_sessions_id'), 'cpe_upload_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpe_upload_sessions_id'), table_name='cpe_upload_sessions')
    op.drop_index(op.f('ix_cpe_upload_sessions_cpa_license_number'), table_name='cpe_upload_sessions')
    op.drop_table('cpe_upload_sessions')
    op.drop_index(op.f('ix_cpe_records_id'), table_name='cpe_records')
    op.drop_index(op.f('ix_cpe_records_cpa_license_number'), table_name='cpe_records')
    op.drop_table('cpe_records')
    # ### end Alembic commands ###
