"""add_user_id_to_cpe_records

Revision ID: d3e0468e8646
Revises: e81aab631892
Create Date: 2025-06-19 21:51:55.080766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e0468e8646'
down_revision: Union[str, None] = 'e81aab631892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpe_records', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cpe_records_user_id'), 'cpe_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'cpe_records', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cpe_records', type_='foreignkey')
    op.drop_index(op.f('ix_cpe_records_user_id'), table_name='cpe_records')
    op.drop_column('cpe_records', 'user_id')
    # ### end Alembic commands ###
